const PROD_API_ENDPOINT = "http://192.168.78.78/server"
const DEV_API_ENDPOINT = "http://localhost:3000"
const SOCKET_HOST = "http://192.168.78.78"

module.exports = {
  PROD_API_ENDPOINT: PROD_API_ENDPOINT,
  DEV_API_ENDPOINT: DEV_API_ENDPOINT,
  SOCKET_HOST: SOCKET_HOST
};