const OPEN_DOOR = 'OPEN_DOOR';
const CLOSE_DOOR = 'CLOSE_DOOR';
const PLAY_ALARM = 'PLAY_ALARM';
const STOP_ALARM = 'STOP_ALARM';

module.exports = {
  OPEN_DOOR: OPEN_DOOR,
  CLOSE_DOOR: CLOSE_DOOR,
  PLAY_ALARM: PLAY_ALARM,
  STOP_ALARM: STOP_ALARM
};