const OPEN_DOOR = 'OPEN_DOOR';
const CLOSE_DOOR = 'CLOSE_DOOR';
const PLAY_ALERT = 'PLAY_ALERT';
const STOP_ALERT = 'STOP_ALERT';
const MAX_PERSONS = 'MAX_PERSONS';
const GET_TOTAL_PERSONS = 'GET_TOTAL_PERSONS';
const TOTAL_PERSONS = 'TOTAL_PERSONS';

module.exports = {
  OPEN_DOOR: OPEN_DOOR,
  CLOSE_DOOR: CLOSE_DOOR,
  PLAY_ALERT: PLAY_ALERT,
  STOP_ALERT: STOP_ALERT,
  MAX_PERSONS: MAX_PERSONS,
  GET_TOTAL_PERSONS: GET_TOTAL_PERSONS,
  TOTAL_PERSONS: TOTAL_PERSONS
};