const OPEN_DOOR = 'OPEN_DOOR';
const CLOSE_DOOR = 'CLOSE_DOOR';
const PLAY_ALERT = 'PLAY_ALERT';
const STOP_ALERT = 'STOP_ALERT';

module.exports = {
  OPEN_DOOR: OPEN_DOOR,
  CLOSE_DOOR: CLOSE_DOOR,
  PLAY_ALERT: PLAY_ALERT,
  STOP_ALERT: STOP_ALERT
};